/**
 * @constant uwpParametersReferenceData
 * @description Object containing all standard possible values for each UWP parameter..
 */

import type { UWPParameterReference } from './types';

export const uwpParametersReferenceData: UWPParameterReference = {
  starport: [
    { code: 'A', description: 'Excellent' },
    { code: 'B', description: 'Good' },
    { code: 'C', description: 'Routine' },
    { code: 'D', description: 'Poor' },
    { code: 'E', description: 'Frontier' },
    { code: 'F', description: 'None' },
    { code: 'X', description: 'No Starport (usually derelict or destroyed)' },
  ],
  size: [
    { code: '0', description: 'Asteroid Belt / No Body' },
    { code: '1', description: '1,600 km diameter' },
    { code: '2', description: '3,200 km diameter' },
    { code: '3', description: '4,800 km diameter' },
    { code: '4', description: '6,400 km diameter' },
    { code: '5', description: '8,000 km diameter' },
    { code: '6', description: '9,600 km diameter' },
    { code: '7', description: '11,200 km diameter' },
    { code: '8', description: '12,800 km diameter' },
    { code: '9', description: '14,400 km diameter' },
    { code: 'A', description: '16,000 km diameter' },
  ],
  atmosphere: [
    { code: '0', description: 'None' },
    { code: '1', description: 'Trace' },
    { code: '2', description: 'Very Thin, Tainted' },
    { code: '3', description: 'Very Thin' },
    { code: '4', description: 'Thin, Tainted' },
    { code: '5', description: 'Thin' },
    { code: '6', description: 'Standard' },
    { code: '7', description: 'Standard, Tainted' },
    { code: '8', description: 'Dense' },
    { code: '9', description: 'Dense, Tainted' },
    { code: 'A', description: 'Exotic' },
    { code: 'B', description: 'Corrosive' },
    { code: 'C', description: 'Insidious' },
  ],
  hydrographics: [
    { code: '0', description: 'Desert World (0-5% liquid surface)' },
    { code: '1', description: '10-20% liquid surface' },
    { code: '2', description: '20-30% liquid surface' },
    { code: '3', description: '30-40% liquid surface' },
    { code: '4', description: '40-50% liquid surface' },
    { code: '5', description: '50-60% liquid surface' },
    { code: '6', description: '60-70% liquid surface' },
    { code: '7', description: '70-80% liquid surface' },
    { code: '8', description: '80-90% liquid surface' },
    { code: '9', description: '90-100% liquid surface (Water World)' },
    { code: 'A', description: 'Ocean World (100% liquid surface)' },
  ],
  population: [
    { code: '0', description: '0-9 inhabitants' },
    { code: '1', description: '10-99 inhabitants' },
    { code: '2', description: '100-999 inhabitants' },
    { code: '3', description: '1,000-9,999 inhabitants' },
    { code: '4', description: '10,000-99,999 inhabitants' },
    { code: '5', description: '100,000-999,999 inhabitants' },
    { code: '6', description: '1,000,000-9,999,999 inhabitants' },
    { code: '7', description: '10,000,000-99,999,999 inhabitants' },
    { code: '8', description: '100,000,000-999,999,999 inhabitants' },
    { code: '9', description: '1,000,000,000-9,999,999,999 inhabitants' },
    { code: 'A', description: '10,000,000,000+ inhabitants' },
  ],
  government: [
    { code: '0', description: 'None (Anarchy)' },
    { code: '1', description: 'Corporate' },
    { code: '2', description: 'Dictatorship' },
    { code: '3', description: 'Self-Perpetuating Oligarchy' },
    { code: '4', description: 'Representative Democracy' },
    { code: '5', description: 'Feudal Technocracy' },
    { code: '6', description: 'Captive Government' },
    { code: '7', description: 'Balkanised' },
    { code: '8', description: 'Communal Anarchy' },
    { code: '9', description: 'Participatory Democracy' },
    { code: 'A', description: 'Technocracy' },
    { code: 'B', description: 'Theocracy' },
    { code: 'C', description: 'Imperial Bureaucracy (or other advanced/unusual types)' },
  ],
  law_level: [
    { code: '0', description: 'No restrictions' },
    { code: '1', description: 'Poison gas, explosives, and WMDs are restricted.' },
    {
      code: '2',
      description: 'Portable energy weapons, bladed weapons longer than 15cm are restricted.',
    },
    { code: '3', description: 'Unconcealed carry of weapons prohibited.' },
    {
      code: '4',
      description:
        'Most personal weapons prohibited. Body pistols, submachine guns, shotguns, and carbines are restricted.',
    },
    { code: '5', description: 'All weapons prohibited. Body armor is restricted.' },
    {
      code: '6',
      description: 'Advanced technology (TL 9+) restricted. Visitors must register their weapons.',
    },
    {
      code: '7',
      description:
        'Highly advanced technology (TL 12+) restricted. Citizens must be licensed to carry any weapon.',
    },
    {
      code: '8',
      description:
        'Restricted activities include most forms of free expression, public assembly, and unauthorized data networks.',
    },
    {
      code: '9',
      description:
        'Restricted activities include all forms of free expression, private organizations, and any contact with outsiders.',
    },
  ],
  tech_level: [
    { code: '0', description: 'Stone Age' },
    { code: '1', description: 'Bronze Age' },
    { code: '2', description: 'Iron Age' },
    { code: '3', description: 'Medieval' },
    { code: '4', description: 'Renaissance' },
    { code: '5', description: 'Industrial' },
    { code: '6', description: 'Pre-Atomic' },
    { code: '7', description: 'Early Atomic' },
    { code: '8', description: 'Fusion' },
    { code: '9', description: 'Interstellar (Jump Drive)' },
    { code: 'A', description: 'Advanced Interstellar' },
    { code: 'B', description: 'Far Advanced Interstellar' },
    { code: 'C', description: 'Cybernetics / Genetics' },
    { code: 'D', description: 'Robotics / AI' },
    { code: 'E', description: 'Exotic / Gravitics' },
    { code: 'F', description: 'Singularities' },
    { code: 'G', description: 'Unknown / Transcendence' },
  ],
  bases: [
    { code: 'N', description: 'Naval Base' },
    { code: 'S', description: 'Scout Base' },
    { code: 'C', description: 'Colonial Government / Customs Base' },
    { code: 'M', description: 'Military Base (specific for a branch, e.g., Marine)' },
    { code: 'D', description: 'Depot (e.g., fuel, supplies)' },
    { code: 'R', description: 'Research Base' },
    { code: 'W', description: 'Way Station' },
    { code: 'P', description: 'Pirate Base' },
    {
      code: 'G',
      description: 'Gas Giant (indicates the world is a gas giant with potential operations)',
    },
    { code: 'T', description: 'Tarnished (implies a failing or decaying base)' },
  ],
  travel_zone: [
    { code: '-', description: 'Green (No restrictions)' },
    { code: 'A', description: 'Amber (Caution, some restrictions apply)' },
    { code: 'R', description: 'Red (Forbidden, travel strictly prohibited)' },
  ],
  trade_codes: [
    { code: 'Ag', description: 'Agricultural' },
    { code: 'As', description: 'Asteroid' },
    { code: 'Ba', description: 'Barren' },
    { code: 'De', description: 'Desert' },
    { code: 'Di', description: 'Dieback' },
    { code: 'Fa', description: 'Farming' },
    { code: 'Fl', description: 'Fluid (Oceanic/Water World)' },
    { code: 'Ga', description: 'Garden' },
    { code: 'He', description: 'Heavily Settled' },
    { code: 'Hi', description: 'High Population' },
    { code: 'Ho', description: 'Homeworld' },
    { code: 'IC', description: 'Industrial (Core)' },
    { code: 'In', description: 'Industrial' },
    { code: 'Lo', description: 'Low Population' },
    { code: 'Lt', description: 'Low Technology' },
    { code: 'Na', description: 'Non-Agricultural' },
    { code: 'Ni', description: 'Non-Industrial' },
    { code: 'Po', description: 'Poor' },
    { code: 'Ri', description: 'Rich' },
    { code: 'Ru', description: 'Rural' },
    { code: 'Sa', description: 'Satellite' },
    { code: 'Sc', description: 'Scientific' },
    { code: 'Wa', description: 'Water World' },
    { code: 'Ya', description: 'Young' },
  ],
  allegiances: [
    { code: 'Im', description: 'Imperial' },
    { code: 'As', description: 'Aslan Hierate' },
    { code: 'Vm', description: 'Vland Sector' },
    { code: 'Zh', description: 'Zhodani Consulate' },
    { code: 'Na', description: 'Non-Aligned' },
    { code: 'Cl', description: 'Client State' },
  ],
};
